# Generated by Django 6.0 on 2025-12-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(upload_to='organizations-logo')),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('show_warning', models.BooleanField(default=False)),
                ('block_access', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
    ]
